// <auto-generated />
using System;
using Axel_ReseauSocial.Api.Domains;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Axel_ReseauSocial.Api.Domains.Migrations
{
    [DbContext(typeof(ReseauSocialDbContext))]
    [Migration("20230713100231_AddRoles")]
    partial class AddRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Axel_ReseauSocial.Api.Models.Localite", b =>
                {
                    b.Property<Guid>("IdLocalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("CP")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("IdLocalite");

                    b.ToTable("Localite", (string)null);
                });

            modelBuilder.Entity("Axel_ReseauSocial.Api.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"), 1L, 1);

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("IdRole");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            Denomination = "Admin"
                        },
                        new
                        {
                            IdRole = 2,
                            Denomination = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
